# Generated by Django 5.2.7 on 2025-12-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_itempedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ej: Palermo, Buenos Aires', max_length=100),
        ),
    ]
