# Generated by Django 5.2.7 on 2025-12-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_producto_fecha_publicacion_producto_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('vino', 'Vino'), ('cerveza', 'Cerveza'), ('licor', 'Licor'), ('energizante', 'Energizante'), ('blanca', 'Bebidas Blancas'), ('snack', 'Snacks'), ('golosina', 'Golosinas'), ('limpieza', 'Limpieza'), ('hogar', 'Hogar'), ('electronica', 'Electrónica'), ('ropa', 'Ropa'), ('calzado', 'Calzado'), ('perfumeria', 'Perfumería'), ('mascotas', 'Mascotas'), ('libros', 'Libros'), ('herramientas', 'Herramientas'), ('juguetes', 'Juguetes'), ('gaming', 'Gaming'), ('otros', 'Otros')], default='licor', max_length=20),
        ),
    ]
