# Generated by Django 5.2.7 on 2025-12-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_cupon_pregunta_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
